// Package agentkey generates and derives the credentials that AI agents use to
// publish reports.
//
// # Why tokens are derived rather than stored
//
// The obvious design is for the server to generate a random token, show it once
// and keep only its hash. That works, but it forces a staging column: between a
// human clicking "approve" and the agent actually claiming the credential, the
// plaintext has to live somewhere, or the agent can never receive it. During
// that window the plaintext is at rest, and a database snapshot taken then
// leaks a usable key.
//
// Instead the token is *derived*:
//
//	token = base64url(HMAC-SHA256(K_derive, "teleport/agent-key/v1|" + appID + "|" + claimSecret))
//
// The claim secret is generated here, handed to the agent once and stored only
// as a hash; K_derive comes from the server secret. Because the derivation is
// deterministic, the server can recompute the token at claim time from material
// it already has, so **no plaintext is ever persisted** — not even briefly.
// Entropy is still the server's to guarantee: a caller cannot weaken the token,
// because the claim secret is generated by us, not proposed by them.
//
// K_derive is a subkey of the session secret rather than the secret itself, so
// the two uses cannot be confused for one another.
package agentkey

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
)

// derivationLabel domain-separates token derivation from session signing, so a
// value that is valid as a session cookie can never be reinterpreted here.
const derivationLabel = "teleport/derive/agent-key/v1"

// tokenLabel is mixed into each token so that the same claim secret under two
// different applications produces two unrelated tokens.
const tokenLabel = "teleport/agent-key/v1"

// claimSecretBytes is the entropy of a claim secret. 32 bytes = 256 bits.
const claimSecretBytes = 32

// prefixLength is how much of a token is kept in the clear for the dashboard to
// display. It is an identifier, not a secret: 8 base64url characters is 48 bits,
// far too little to mount a guess against a 256-bit space, and enough for a
// human to tell two keys apart.
const prefixLength = 8

// KDerive returns the subkey used for token derivation.
//
// Deriving a subkey rather than using the session secret directly means a leak
// of one usage does not directly hand over the other, and it keeps the secret
// material out of any code path that merely wants a stable key.
func KDerive(sessionSecret string) []byte {
	return hmacSHA256([]byte(sessionSecret), derivationLabel)
}

// DeriveToken recomputes the bearer token for an application.
//
// Both the application id and the claim secret are inputs, so a token cannot be
// produced from an application id alone — an attacker who learns the id (it
// appears in URLs and logs) still cannot reconstruct the credential.
func DeriveToken(kDerive []byte, applicationID, claimSecret string) string {
	mac := hmac.New(sha256.New, kDerive)
	mac.Write([]byte(tokenLabel))
	mac.Write([]byte("|"))
	mac.Write([]byte(applicationID))
	mac.Write([]byte("|"))
	mac.Write([]byte(claimSecret))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
}

// HashToken returns the value stored in agent_keys.token_hash.
//
// SHA-256 without a salt is the right choice here, unlike for passwords: the
// input is a 256-bit uniformly random value, so there is no dictionary to
// attack and no rainbow table to build. It also has to be deterministic,
// because the lookup is by hash — a per-row salt would make that impossible.
func HashToken(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

// Prefix returns the display prefix of a token.
func Prefix(token string) string {
	if len(token) <= prefixLength {
		return token
	}
	return token[:prefixLength]
}

// NewToken returns a fresh, high-entropy bearer token.
//
// Used for the manual hand-over path, where a human asks the dashboard to mint a
// key outright and copies the result to the agent. Nothing needs to be derived
// here, so the value is simply random — and it is never persisted in the clear,
// only its hash.
func NewToken() (string, error) {
	return randomBase64URL(claimSecretBytes)
}

// NewClaimSecret returns a fresh, high-entropy claim secret.
func NewClaimSecret() (string, error) {
	return randomBase64URL(claimSecretBytes)
}

// EqualHash compares two hex hashes in constant time.
//
// Used when checking a presented claim secret against the stored hash. A plain
// == would let an attacker recover the hash byte by byte from response timing.
func EqualHash(a, b string) bool {
	return subtle.ConstantTimeCompare([]byte(a), []byte(b)) == 1
}

// NewID returns a random UUID v4 string.
func NewID() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	dst := make([]byte, 36)
	hex.Encode(dst[0:8], b[0:4])
	dst[8] = '-'
	hex.Encode(dst[9:13], b[4:6])
	dst[13] = '-'
	hex.Encode(dst[14:18], b[6:8])
	dst[18] = '-'
	hex.Encode(dst[19:23], b[8:10])
	dst[23] = '-'
	hex.Encode(dst[24:36], b[10:16])
	return string(dst), nil
}

func randomBase64URL(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

func hmacSHA256(secret []byte, data string) []byte {
	mac := hmac.New(sha256.New, secret)
	mac.Write([]byte(data))
	return mac.Sum(nil)
}
