/**
 * Ambient declarations merged into the Wrangler-generated `Env` interface.
 *
 * `worker-configuration.d.ts` is generated by `npm run cf-typegen` and covers
 * everything declared in wrangler.toml. Secrets are deliberately absent from
 * wrangler.toml, so they are declared here instead.
 *
 * Set them with `npx wrangler secret put <NAME>` (production) or in `.dev.vars`
 * (local development). See `.dev.vars.example`.
 */
interface Env {
  /** Bearer secret required by POST /api/reports. */
  AGENT_SECRET_KEY: string;
  /** HMAC key used to sign the dashboard session cookie. */
  SESSION_SECRET: string;
  /** PBKDF2 hash for the /dashboard password login, `pbkdf2$<iterations>$<salt>$<hash>`. */
  ADMIN_PASSWORD_HASH: string;
}
